#!/usr/bin/env python
# coding: utf-8
import numpy as np
import os
import pandas as pd
import shutil
from pymatgen import Structure, Lattice,MPRester
from pymatgen import MPRester
from pymatgen.core.surface import Slab, SlabGenerator
mpr = MPRester('Rw9SXoXqU8sgRx9v')

###read 'List.txt' file generated by hse_retrivial.py
dir_='List.txt'
file = pd.read_csv(dir_, sep=',', header=None)
np_file=np.asarray(file)
mp_list=np_file[:,0]

#### miller index #####
number1 = input("miller index a : ")
number2 = input("miller index b : ")
number3 = input("miller index c : ")
number1 = int(number1)
number2 = int(number2)
number3 = int(number3)
matrix = [number1,number2,number3]

#### Surface generate function ####
original_dir=os.getcwd()
for mp in mp_list:
    os.chdir(mp)
    mp1=str(mp)+".vasp"
    #print(mp1)
    struct = Structure.from_file("CONTCAR")
    sgen = SlabGenerator(struct,matrix,12,20,primitive=False)
    a = sgen.get_slab()
    c = a.get_sorted_structure()
    d = c.get_orthogonal_c_slab()
    d.to(filename="POSCAR.surface")
    os.rename('POSCAR.surface',mp1)
    shutil.copy(mp1,original_dir)
    os.chdir(original_dir)

print('The slab was created successfully created with miller index:'+ str(matrix))
